# do the below changes in code
# import sys

# def main():
#     mode = sys.argv[1] if len(sys.argv) > 1 else "pre"

#     if mode == "pre":
#         print("Running Pre-Patch script")
#         result = lambda_handler({}, None)
#         print("Pre-Patch notification completed successfully:", result)

#     elif mode == "post":
#         print("Running Post-Patch script")
#         post_patch_function()
#         print("Post-Patch script completed successfully")

#     else:
#         raise ValueError("Invalid mode. Use 'pre' or 'post'")

# if __name__ == "__main__":
#     main()





name: Patch Notifications

on:
  schedule:
    # Pre-Patch at 10:00 AM
    - cron: "0 10 * * *"
    # Post-Patch at 5:00 PM
    - cron: "0 17 * * *"
  workflow_dispatch:  # manual trigger if needed

jobs:
  run-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pre or Post Patch
        run: |
          if [ "${{ github.event.schedule }}" == "0 10 * * *" ]; then
            python patch_script.py pre
          else
            python patch_script.py post
          fi
